apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testgo
  name: testgo
spec:
  containers:
  - image: testgo:v1
    imagePullPolicy: Never
    name: testgo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
