apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testscript
  name: testscript
spec:
  containers:
  - image: script:latest
    imagePullPolicy: IfNotPresent
    name: testscript
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
